#!/usr/bin/env python3
# encoding=UTF-8

import argparse
import math

def factor(n):
    sqrt = math.isqrt
    if n < 0:
        (p, q) = factor(-n)
        return (-p, q)
    if n <= 3:
        return (1, n)
    if (n & 1) == 0:
        return (2, n // 2)
    a = sqrt(n)
    bb = (a ** 2) - n
    if bb < 0:
        bb += 2 * a + 1
        a += 1
    while True:
        b = sqrt(bb)
        if b ** 2 == bb:
            p = a - b
            q = a + b
            assert p * q == n
            return (p, q)
        bb += 2 * a + 1
        a += 1

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('n', metavar='N', type=int)
    args = ap.parse_args()
    for i in factor(args.n):
        print(i)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
